// Generated by CoffeeScript 1.11.1
var aa, bind, onlyBind;

aa = require('./index');

onlyBind = /^\{\{[^\{^\}]+\}\}$/;

console.log(onlyBind.test("{{true}}"));

bind = /\{\{.+?\}\}/g;

console.log(bind.test("left{{true}}right"));
