// Generated by CoffeeScript 1.11.1
var bindL, bindR, clearBindLR, convertMixed, convertOnly, mixedBind, onlyBind;

onlyBind = /^\{\{[^\{^\}]+\}\}$/;

mixedBind = /\{\{.+?\}\}/g;

bindL = /\{\{/g;

bindR = /\}\}/g;

clearBindLR = function(str) {
  return str.replace(bindL, "").replace(bindR, "");
};

convertOnly = function(data) {
  return "{" + (clearBindLR(data)) + "}";
};

convertMixed = function(data) {
  var bd, binds, i, item, len, noBinds, ret;
  binds = data.match(mixedBind);
  noBinds = data.split(mixedBind);
  ret = [];
  for (i = 0, len = noBinds.length; i < len; i++) {
    item = noBinds[i];
    bd = binds.shift();
    ret.push("'" + item + "'" + (bd ? "+(" + (clearBindLR(bd)) + ")" : ''));
  }
  return "{" + (ret.join('+')) + "}";
};

module.exports = function(data) {
  if (onlyBind.test(data)) {
    return convertOnly(data);
  } else if (mixedBind.test(data)) {
    return convertMixed(data);
  }
};
